print("Hello World")

print("Ilona Mykhailova")
print("FirstName LastName")
print("Serhii Basik")
print("Artem Bystritskyi")
print("Ivashchenko Daniil")
print('Oleksiy Didenko')
print("Oleksandr Kachanov")
print("Maksym Vizniak")