Imports System

Module Program
    Sub Main(args As String())
        Console.WriteLine("Hello World!")
        Console.WriteLine("Sergey Ovchinnikov")
		Console.WriteLine("Maria Lutskevich")
        Console.WriteLine("Mashkov Andriy")
		Console.WriteLine("Albina Suyusanova")
		Console.WriteLine("Nikita Linovytskyi")
        Console.WriteLine("Zhohan Vsevolod")
        Console.WriteLine("Bezsmertnyi Oleksandr")
        Console.WriteLine("Sergey Ovchinnikov")
		Console.WriteLine("Maria Lutskevich")
        Console.WriteLine("Ovchynnikov Serhii")
        Console.WriteLine("Mashkov Andriy")
        Console.WriteLine("Nikita Linovytskyi")
        Console.WriteLine("Igor Gulyaschy")
		Console.WriteLine("Nikita Linovytskyi")
        Console.WriteLine("Anna Morhunova")
        Console.WriteLine("Zhohan Vsevolod")
        Console.WriteLine("Andrei Ishchenko")
		Console.WriteLine("Anastasia Gritsenko")
        Console.WriteLine("Dzigil Uliana")
	Console.WriteLine("Albina Suyusanova")
	Console.WriteLine("Albina Suyusanova")
	Console.WriteLine("Albina Suyusanova")
	Console.WriteLine("Anhelina Liaskovych    ")
    End Sub
End Module
